### ISSUE TITLE
ControlNet: Lineart models don't work

### ISSUE THREAD

**Issue by Miraihi** [DrCyanide/cyanic-sd-krita#13]
Simply, no lineart models work (Preprocessing does. Also the models work in the stock Auto-webui.)

The models in question:
[control_v11p_sd15s2_lineart_anime_fp16](https://huggingface.co/comfyanonymous/ControlNet-v1-1_fp16_safetensors/blob/main/control_v11p_sd15s2_lineart_anime_fp16.safetensors)
[control_v11p_sd15_lineart_fp16](https://huggingface.co/comfyanonymous/ControlNet-v1-1_fp16_safetensors/blob/main/control_v11p_sd15_lineart_fp16.safetensors)

Just to be clear: This is not the new problem, it's been that way since the beginning. Just forgot to report it.

The log I'm getting from the SD console:

```
*** Error running process: E:\AI\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\controlnet.py
    Traceback (most recent call last):
      File "E:\AI\stable-diffusion-webui\modules\scripts.py", line 619, in process
        script.process(p, *script_args)
      File "E:\AI\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\controlnet.py", line 977, in process
        self.controlnet_hack(p)
      File "E:\AI\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\controlnet.py", line 966, in controlnet_hack
        self.controlnet_main_entry(p)
      File "E:\AI\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\controlnet.py", line 808, in controlnet_main_entry
        detected_map, is_image = preprocessor(
      File "E:\AI\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\utils.py", line 75, in decorated_func
        return cached_func(*args, **kwargs)
      File "E:\AI\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\utils.py", line 63, in cached_func
        return func(*args, **kwargs)
      File "E:\AI\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\global_state.py", line 35, in unified_preprocessor
        return preprocessor_modules[preprocessor_name](*args, **kwargs)
      File "E:\AI\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\processor.py", line 433, in lineart_anime
        img, remove_pad = resize_image_with_pad(img, res)
      File "E:\AI\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\processor.py", line 27, in resize_image_with_pad
        img = cv2.resize(img, (W_target, H_target), interpolation=interpolation)
    cv2.error: OpenCV(4.8.0) D:\a\opencv-python\opencv-python\opencv\modules\imgproc\src\resize.cpp:4065: error: (-215:Assertion failed) inv_scale_x > 0 in function 'cv::resize'
```

**Comment by DrCyanide** [comment]
I was using the wrong API name for ControlNet's preprocessor resolution. This should be fixed now.
